// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type Global = Collections['globals']['schema']['_output']
export declare const globals: Global

export type Post = Collections['posts']['schema']['_output']
export declare const posts: Post[]

export type Author = Collections['authors']['schema']['_output']
export declare const authors: Author[]

export type Column = Collections['columns']['schema']['_output']
export declare const columns: Column[]

export type Category = Collections['categories']['schema']['_output']
export declare const categories: Category[]

export type Tag = Collections['tags']['schema']['_output']
export declare const tags: Tag[]
