// This file is generated by Velite

export { default as globals } from './globals.json'
export { default as pages } from './pages.json'
export { default as posts } from './posts.json'
export { default as authors } from './authors.json'
export { default as columns } from './columns.json'
export { default as categories } from './categories.json'
export { default as tags } from './tags.json'
export { default as tagDict } from './tagDict.json'
export { default as galleries } from './galleries.json'