// This file is generated by Velite

export { default as posts } from './posts.json'
export { default as authors } from './authors.json'
export { default as categories } from './categories.json'
export { default as tags } from './tags.json'